name: motafawk
description: Motafawk App project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

#  cloud_firestore: 4.4.3
  firebase_messaging: ^14.7.4
  awesome_notifications: ^0.8.2
  flutter_downloader: ^1.11.5
#  flutter_downloader: ^1.11.4
#  flutter_downloader: 1.8.4
  permission_handler: ^11.1.0
  get: ^4.6.6
  get_storage: ^2.0.3
  path_provider: ^2.1.1
  http: ^1.0.0
  dio: ^5.2.1+1
  fluttertoast: ^8.2.4
  url_launcher: ^6.1.11
  awesome_dialog: ^3.1.0
  share:
  font_awesome_flutter: ^10.6.0
  jiffy: any
  sqflite: ^2.2.8+4
  cached_network_image: ^3.3.0
  swipe_image_gallery: ^0.8.3
  badges: ^3.1.1
  like_button: ^2.0.5
#  flutter_pdfview: 1.3.1
  flutter_cache_manager: 3.3.1
  syncfusion_flutter_pdfviewer: 23.2.6
  syncfusion_flutter_pdf: 23.2.6
  syncfusion_flutter_core: 23.2.6
  printing: ^5.11.1
  percent_indicator: 4.2.3
  open_file: 3.3.2
  flutter_animate: ^4.2.0+1
  dropdown_search:
  curved_navigation_bar:
  flutter_svg: ^2.0.7

  google_mobile_ads: ^3.1.0
  package_info_plus: ^4.2.0
  confetti: ^0.7.0
  audioplayers: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


#  flutter_native_splash:
#flutter_native_splash:
#  color: "#ffffff"
#  image: "assets/images/logo.png"
#  # flutter pub run flutter_native_splash:create

#  flutter_launcher_icons:
#flutter_icons:
#  android: "ic_launcher"
#  ios: true
#  image_path: "assets/images/icon.png"
#  # flutter pub run flutter_launcher_icons

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Almaria
      fonts:
        - asset: assets/fonts/Almaria/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almaria/Almarai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Almaria/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almaria/Almarai-ExtraBold.ttf
          weight: 800


